require("sinatra")
require("sinatra/reloader")
also_reload("lib/**/*.rb")
require("./lib/book")
require("./lib/author")
require("./lib/authors_books")
require("./lib/patron")
require("./lib/checkout")
require("pg")

DB = PG.connect({:dbname => "library_systems"})
